# Generated by Django 2.2.16 on 2020-10-03 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200925_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trans_user_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
