# Generated by Django 2.2.16 on 2020-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201007_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
