# Generated by Django 2.2.23 on 2021-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='can_have_items',
            field=models.BooleanField(default=True),
        ),
    ]
