# Generated by Django 2.2.24 on 2021-09-06 07:39

from django.db import migrations
import django_extensions.db.fields

from home.models import Item

def migrate_data_forward(apps, schema_editor):
    for instance in Item.objects.all():
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210630_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='serial_slug',
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, default=None,
                editable=False, null=True,
                populate_from='serial'),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
